kind: Deployment
apiVersion: apps/v1
metadata:
  name: readarr
  labels:
    app: readarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: readarr
  template:
    metadata:
      labels:
        app: readarr
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - macpro01
      containers:
      - name: readarr
        image: hotio/readarr:nightly
        imagePullPolicy: Always
        ports:
          - containerPort: 8787
        env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: TZ
            value: "America/New_York"
          - name: UMASK
            value: "000"
          - name: DEBUG
            value: "no"
        volumeMounts:
          - mountPath: /config
            name: config
          - mountPath: /books
            name: books
          - mountPath: /downloads
            name: downloads
        livenessProbe:
          httpGet:
            port: 8787
            path: /
            httpHeaders:
              - name: Liveness-Header
                value: Readarr-Probe
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
      volumes:
      - name: config
        hostPath:
          path: /data/readarr
      - name: books
        hostPath:
          path: /mnt/share/eBooks
      - name: downloads
        hostPath:
          path: /mnt/share/Downloads