apiVersion: v1
kind: Service
metadata:
  name: transmission
  namespace: default
spec:
  selector:
    app: transmission
  ports:
  - name: "9091"
    port: 9091
    targetPort: 9091
  - name: "51413-tcp"
    port: 51413
    targetPort: 51413
    protocol: TCP
  - name: "51413-udp"
    port: 51413
    targetPort: 51413
    protocol: UDP