apiVersion: v1
kind: Service
metadata:
  name: transmission
  namespace: default
spec:
  selector:
    app: transmission
  ports:
  - port: 9091
    targetPort: 9091
  - protocol: UDP
    port: 51413
    targetPort: 51413