kind: Deployment
apiVersion: apps/v1
metadata:
  name: wallabag
  labels:
    app: wallabag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallabag
  template:
    metadata:
      labels:
        app: wallabag
    spec:
      containers:
      - name: wallabag
        image: wallabag/wallabag
        ports:
          - containerPort: 80
        env:
          - name: SYMFONY__ENV__DOMAIN_NAME
            value: "http://wallabag.lan"
          - name:  POPULATE_DATABASE
            value: "True"
        volumeMounts:
          - name: data
            mountPath: /var/www/wallabag/data
        livenessProbe:
          httpGet:
            port: 80
            path: /
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: wallabag