kind: Deployment
apiVersion: apps/v1
metadata:
  name: radarr
  namespace: default
  labels:
    app: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - macpro01
      containers:
      - name: radarr
        image: linuxserver/radarr:nightly
        imagePullPolicy: Always
        ports:
          - containerPort: 7878
        env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: TZ
            value: "America/New_York"
        volumeMounts:
          - mountPath: /config
            name: config
          - mountPath: /downloads
            name: downloads
          - mountPath: /movies
            name: movies
      volumes:
      - name: config
        hostPath:
          path: /data/radarr
      - name: downloads
        hostPath:
          path: /mnt/share/Downloads
      - name: movies
        hostPath:
          path: /mnt/share/Movies