kind: Deployment
apiVersion: apps/v1
metadata:
  name: lidarr
  namespace: default
  labels:
    app: lidarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lidarr
  template:
    metadata:
      labels:
        app: lidarr
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - macpro01
      containers:
      - name: lidarr
        image: linuxserver/lidarr:nightly
        imagePullPolicy: Always
        ports:
          - containerPort: 8686
        env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: TZ
            value: "America/New_York"
        volumeMounts:
          - mountPath: /config
            name: config
          - mountPath: /downloads
            name: downloads
          - mountPath: /music
            name: music
        livenessProbe:
          httpGet:
            port: 8686
            path: /
            httpHeaders:
              - name: Liveness-Header
                value: Readarr-Probe
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
      volumes:
      - name: config
        hostPath:
          path: /data/lidarr
      - name: downloads
        hostPath:
          path: /mnt/share/Downloads
      - name: music
        hostPath:
          path: /mnt/share/Music