kind: Deployment
apiVersion: apps/v1
metadata:
  name: sonarr
  namespace: default
  labels:
    app: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - macpro01
      containers:
      - name: sonarr
        image: hotio/sonarr:nightly
        imagePullPolicy: Always
        ports:
          - containerPort: 8989
        env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: TZ
            value: "America/New_York"
        volumeMounts:
          - mountPath: /config
            name: config
          - mountPath: /downloads
            name: downloads
          - mountPath: /tv
            name: tv
      volumes:
      - name: config
        hostPath:
          path: /data/sonarr
      - name: downloads
        hostPath:
          path: /mnt/share/Downloads
      - name: tv
        hostPath:
          path: /mnt/share/Television